"""
Alternative radio tasks using direct archive URL patterns
Based on the existing files in data/radio/ which follow the pattern:
YYYYMMDDHHMM-feedId-12145.mp3
"""
import os
import json
import time
import logging
import requests
from datetime import datetime, timedelta
from typing import Dict, Any, List, Optional
from pathlib import Path
from celery import current_task

from app.workers.celery_app import celery_app

logger = logging.getLogger(__name__)

# Data paths - use absolute path for GPU worker compatibility
RADIO_DATA_PATH = Path("/app/data/radio/phoenix_pd")
RADIO_DATA_PATH.mkdir(parents=True, exist_ok=True)

# Archive settings
PHOENIX_PD_FEED_ID = "12145"
ARCHIVE_BASE_URL = "https://m.broadcastify.com/archives/download"

# Rate limiting settings
DOWNLOAD_DELAY_SECONDS = 3  # Delay between downloads to be respectful
MAX_DOWNLOADS_PER_RUN = 10  # Limit downloads per task run


@celery_app.task(bind=True, name="download_phoenix_pd_archives")
def download_phoenix_pd_archives(
    self,
    feed_id: str = PHOENIX_PD_FEED_ID,
    max_downloads: int = MAX_DOWNLOADS_PER_RUN,
    hours_back: int = 24,
) -> Dict[str, Any]:
    """
    Download Phoenix PD archives using direct URL patterns

    This task attempts to download archives based on the observed URL pattern.
    Archives appear to be available at specific time intervals.

    Args:
        feed_id: Broadcastify feed ID
        max_downloads: Maximum number of files to download in this run
        hours_back: Number of hours back to check for archives

    Returns:
        Dictionary with download results
    """
    downloaded_files = []
    skipped_files = []
    errors = []
    attempted_urls = []

    session = requests.Session()
    session.headers.update(
        {
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"
        }
    )

    try:
        # Update task state
        current_task.update_state(
            state="PROCESSING",
            meta={
                "status": "Starting archive download",
                "downloaded": 0,
                "skipped": 0,
            },
        )

        # Calculate time range
        end_time = datetime.now()
        start_time = end_time - timedelta(hours=hours_back)

        downloads_count = 0
        current_time = end_time

        # Archives appear to be created at regular intervals (likely every 30 minutes or hour)
        # Based on existing files: 202509062247, 202509062346, 202509070046, 202509070116
        # This suggests roughly hourly archives

        while current_time >= start_time and downloads_count < max_downloads:
            # Round to nearest 30 minutes for archive availability
            archive_time = current_time.replace(second=0, microsecond=0)
            if archive_time.minute >= 30:
                archive_time = archive_time.replace(minute=30)
            else:
                archive_time = archive_time.replace(minute=0)

            # Format timestamp for filename (YYYYMMDDHHMM)
            timestamp = archive_time.strftime("%Y%m%d%H%M")

            # Generate a pseudo-random ID based on timestamp (simplified approach)
            # In reality, these IDs are generated by Broadcastify
            archive_id = str(hash(timestamp) % 1000000).zfill(6)

            # Construct filename
            filename = f"{timestamp}-{archive_id}-{feed_id}.mp3"
            file_path = RADIO_DATA_PATH / filename

            # Skip if already downloaded
            if file_path.exists():
                logger.info(f"Skipping existing file: {filename}")
                skipped_files.append(str(file_path))
                current_time -= timedelta(minutes=30)
                continue

            # Try to construct a download URL
            # Note: This is a simplified approach - actual URLs may require authentication
            download_url = f"{ARCHIVE_BASE_URL}/{archive_id}"
            attempted_urls.append(download_url)

            current_task.update_state(
                state="PROCESSING",
                meta={
                    "status": f"Checking archive for {timestamp}",
                    "downloaded": len(downloaded_files),
                    "skipped": len(skipped_files),
                },
            )

            try:
                # Attempt download
                logger.info(f"Attempting to download: {filename}")
                response = session.head(download_url, timeout=10)

                if response.status_code == 200:
                    # Download the file
                    response = session.get(download_url, stream=True, timeout=30)

                    if response.status_code == 200:
                        with open(file_path, "wb") as f:
                            for chunk in response.iter_content(chunk_size=8192):
                                f.write(chunk)

                        downloaded_files.append(str(file_path))
                        downloads_count += 1
                        logger.info(f"Downloaded: {filename}")

                        # Rate limiting
                        time.sleep(DOWNLOAD_DELAY_SECONDS)

            except requests.RequestException as e:
                # This is expected for many URLs as we're guessing
                logger.debug(f"Could not download {filename}: {str(e)}")

            # Move to previous time slot
            current_time -= timedelta(minutes=30)

        # Log attempted URLs for debugging
        if not downloaded_files and attempted_urls:
            logger.info(f"No files downloaded. Attempted URLs: {attempted_urls[:5]}")
            logger.info(
                "Note: Direct download may require premium account or authentication"
            )

        # Final state update
        current_task.update_state(
            state="SUCCESS",
            meta={
                "status": "Completed",
                "downloaded": len(downloaded_files),
                "skipped": len(skipped_files),
                "errors": len(errors),
                "note": "Direct download may require premium account"
                if not downloaded_files
                else None,
            },
        )

        return {
            "status": "success",
            "downloaded_files": downloaded_files,
            "skipped_files": skipped_files,
            "errors": errors,
            "total_downloaded": len(downloaded_files),
            "total_skipped": len(skipped_files),
            "note": "Archives may require premium Broadcastify account for download"
            if not downloaded_files
            else None,
        }

    except Exception as exc:
        logger.error(f"Archive download task failed: {str(exc)}", exc_info=True)

        current_task.update_state(
            state="FAILURE",
            meta={
                "status": "failed",
                "error": str(exc),
            },
        )

        raise exc
    finally:
        session.close()


@celery_app.task(
    bind=True,
    name="transcribe_phoenix_pd_archives",
    time_limit=7200,  # 2 hours hard limit
    soft_time_limit=6600,  # 1 hour 50 minutes soft limit
)
def transcribe_phoenix_pd_archives(
    self,
    directory_path: str = str(RADIO_DATA_PATH),
    model_name: str = "base",
    batch_size: int = 5,
) -> Dict[str, Any]:
    """
    Transcribe MP3 files in the Phoenix PD radio archives directory

    Args:
        directory_path: Path to directory containing MP3 files
        model_name: Whisper model to use (tiny, base, small, medium, large)
        batch_size: Maximum number of files to process in one run

    Returns:
        Dictionary with transcription results
    """
    transcribed_files = []
    skipped_files = []
    errors = []

    try:
        # Load Whisper model
        current_task.update_state(
            state="PROCESSING",
            meta={
                "status": f"Loading Whisper model: {model_name}",
                "transcribed": 0,
                "skipped": 0,
            },
        )

        # Load model with GPU support
        import torch
        import whisper

        device = "cuda" if torch.cuda.is_available() else "cpu"
        model = whisper.load_model(model_name, device=device)
        logger.info(f"Loaded Whisper model: {model_name} on device: {device}")
        if device == "cuda":
            logger.info(f"GPU: {torch.cuda.get_device_name(0)}")
        else:
            logger.warning("CUDA not available! Running on CPU (will be very slow)")

        # Get list of MP3 files
        mp3_files = list(Path(directory_path).glob("*.mp3"))

        # Filter to only untranscribed files
        files_to_process = []
        for mp3_file in mp3_files:
            # Check if transcription already exists (as .json file)
            json_file = mp3_file.with_suffix(".json")
            if not json_file.exists():
                files_to_process.append(mp3_file)
            else:
                skipped_files.append(str(mp3_file))

        # Limit to batch size
        files_to_process = files_to_process[:batch_size]

        logger.info(f"Found {len(files_to_process)} files to transcribe")

        for idx, mp3_file in enumerate(files_to_process, 1):
            try:
                current_task.update_state(
                    state="PROCESSING",
                    meta={
                        "status": f"Transcribing file {idx}/{len(files_to_process)}: {mp3_file.name}",
                        "transcribed": len(transcribed_files),
                        "skipped": len(skipped_files),
                        "current_file": mp3_file.name,
                        "progress": idx / len(files_to_process) * 100,
                    },
                )

                logger.info(f"Transcribing: {mp3_file.name}")

                # Transcribe with Whisper - optimized for police radio
                # FP16 is automatically used on CUDA if available
                result = model.transcribe(
                    str(mp3_file),
                    language="en",
                    task="transcribe",
                    verbose=False,
                    temperature=0,  # More deterministic results for technical content
                    condition_on_previous_text=True,  # Better context for unit numbers/callsigns
                    initial_prompt="Phoenix Police Department radio communications with unit numbers, callsigns, addresses, and dispatch codes.",
                    compression_ratio_threshold=2.4,  # Detect repetition/hallucination
                    logprob_threshold=-1.0,  # Filter low confidence segments
                    no_speech_threshold=0.6,  # Handle static and silence
                    beam_size=5,  # Beam search for better accuracy
                )

                # Extract timestamp from filename (YYYYMMDDHHMM format)
                filename_parts = mp3_file.stem.split("-")
                if filename_parts and len(filename_parts[0]) == 12:
                    timestamp_str = filename_parts[0]
                    recording_time = datetime.strptime(timestamp_str, "%Y%m%d%H%M")
                else:
                    recording_time = datetime.fromtimestamp(mp3_file.stat().st_mtime)

                # Prepare transcription data with timestamps
                transcription_data = {
                    "filename": mp3_file.name,
                    "recording_time": recording_time.isoformat(),
                    "transcribed_at": datetime.now().isoformat(),
                    "model": model_name,
                    "text": result["text"],
                    "segments": [],
                    "metadata": {
                        "feed_id": PHOENIX_PD_FEED_ID,
                        "feed_name": "Phoenix Police",
                        "duration": result.get("duration"),
                    },
                }

                # Add segment details with timestamps
                for segment in result.get("segments", []):
                    transcription_data["segments"].append(
                        {
                            "id": segment.get("id"),
                            "start": segment.get("start"),
                            "end": segment.get("end"),
                            "text": segment.get("text", "").strip(),
                        }
                    )

                # Save transcription as JSON
                json_file = mp3_file.with_suffix(".json")
                with open(json_file, "w") as f:
                    json.dump(transcription_data, f, indent=2)

                # Also save plain text version for easy reading
                txt_file = mp3_file.with_suffix(".txt")
                with open(txt_file, "w") as f:
                    f.write("Phoenix Police Radio Archive Transcription\n")
                    f.write(f"{'=' * 60}\n")
                    f.write(f"File: {mp3_file.name}\n")
                    f.write(
                        f"Recording Time: {recording_time.strftime('%Y-%m-%d %H:%M')}\n"
                    )
                    f.write(
                        f"Transcribed: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n"
                    )
                    f.write(f"Model: {model_name}\n")
                    f.write(f"{'=' * 60}\n\n")

                    # Write segments with timestamps
                    f.write("TIMESTAMPED TRANSCRIPT:\n\n")
                    for segment in transcription_data["segments"]:
                        start_time = segment["start"]
                        end_time = segment["end"]
                        # Format timestamps as MM:SS
                        start_str = (
                            f"{int(start_time//60):02d}:{int(start_time%60):02d}"
                        )
                        end_str = f"{int(end_time//60):02d}:{int(end_time%60):02d}"
                        f.write(f"[{start_str} - {end_str}] {segment['text']}\n")

                    f.write("\n" + "=" * 60 + "\n")
                    f.write("FULL TEXT:\n\n")
                    f.write(result["text"])

                transcribed_files.append(str(mp3_file))
                logger.info(f"Transcribed: {mp3_file.name}")

            except Exception as e:
                logger.error(f"Error transcribing {mp3_file.name}: {str(e)}")
                errors.append(f"Error transcribing {mp3_file.name}: {str(e)}")

        # Final state update
        current_task.update_state(
            state="SUCCESS",
            meta={
                "status": "Completed",
                "transcribed": len(transcribed_files),
                "skipped": len(skipped_files),
                "errors": len(errors),
            },
        )

        return {
            "status": "success",
            "transcribed_files": transcribed_files,
            "skipped_files": skipped_files,
            "errors": errors,
            "total_transcribed": len(transcribed_files),
            "total_skipped": len(skipped_files),
        }

    except Exception as exc:
        logger.error(f"Transcription task failed: {str(exc)}", exc_info=True)

        current_task.update_state(
            state="FAILURE",
            meta={
                "status": "failed",
                "error": str(exc),
            },
        )

        raise exc
