"""Add radio transcription models for analysis

Revision ID: 21a584524a8e
Revises: ccca6db6c0ac
Create Date: 2025-10-22 08:35:14.856332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21a584524a8e'
down_revision: Union[str, None] = 'ccca6db6c0ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_phoenix_neighborhoods_boundary', table_name='phoenix_neighborhoods', postgresql_using='gist')
    op.drop_index('idx_phoenix_neighborhoods_name', table_name='phoenix_neighborhoods')
    op.drop_table('phoenix_neighborhoods')
    op.drop_index('idx_flight_positions_lat_lon', table_name='flight_positions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_flight_positions_lat_lon', 'flight_positions', ['latitude', 'longitude'], unique=False)
    op.create_table('phoenix_neighborhoods',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Village name (e.g., Maryvale, Ahwatukee Foothills)'),
    sa.Column('object_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('acres', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True, comment='Area of village in acres'),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('insert_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('update_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('boundary', geoalchemy2.types.Geography(geometry_type='POLYGON', srid=4326, from_text='ST_GeogFromText', name='geography', nullable=False), autoincrement=False, nullable=False, comment='Village boundary polygon in WGS84 (SRID 4326)'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='phoenix_neighborhoods_pkey'),
    sa.UniqueConstraint('name', name='phoenix_neighborhoods_name_key'),
    comment='Official Phoenix urban village boundaries from City of Phoenix Open Data'
    )
    op.create_index('idx_phoenix_neighborhoods_name', 'phoenix_neighborhoods', ['name'], unique=False)
    op.create_index('idx_phoenix_neighborhoods_boundary', 'phoenix_neighborhoods', ['boundary'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###
