"""Add operator field to aircraft table

Revision ID: 22a99ea3d686
Revises: e9e85a9bf3fd
Create Date: 2025-09-12 04:02:01.333815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "22a99ea3d686"
down_revision: Union[str, None] = "e9e85a9bf3fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "aircraft", sa.Column("operator", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("aircraft", "operator")
    # ### end Alembic commands ###
