"""Add missing AGL and operator columns

Revision ID: 376fc70067b9
Revises: 8740c54ea738
Create Date: 2025-10-12 07:12:21.641896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '376fc70067b9'
down_revision: Union[str, None] = '8740c54ea738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_logs_category_created', table_name='system_logs')
    op.drop_index('idx_logs_created_level', table_name='system_logs')
    op.drop_index('idx_logs_level_category', table_name='system_logs')
    op.drop_index('ix_system_logs_category', table_name='system_logs')
    op.drop_index('ix_system_logs_created_at', table_name='system_logs')
    op.drop_index('ix_system_logs_flight_id', table_name='system_logs')
    op.drop_index('ix_system_logs_id', table_name='system_logs')
    op.drop_index('ix_system_logs_level', table_name='system_logs')
    op.drop_index('ix_system_logs_registration', table_name='system_logs')
    op.drop_index('ix_system_logs_source', table_name='system_logs')
    op.drop_table('system_logs')
    op.alter_column('aircraft', 'is_phoenix_pd',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('aircraft', 'has_flir',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('aircraft', 'has_spotlight',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('aircraft', 'has_loudspeaker',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('aircraft', 'hourly_operating_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('aircraft', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint('aircraft_icao_code_key', 'aircraft', type_='unique')
    op.drop_constraint('aircraft_registration_key', 'aircraft', type_='unique')
    op.drop_index('idx_aircraft_icao', table_name='aircraft')
    op.drop_index('idx_aircraft_phoenix_pd', table_name='aircraft')
    op.drop_index('idx_aircraft_registration', table_name='aircraft')
    op.create_index(op.f('ix_aircraft_icao_code'), 'aircraft', ['icao_code'], unique=True)
    op.create_index(op.f('ix_aircraft_id'), 'aircraft', ['id'], unique=False)
    op.create_index(op.f('ix_aircraft_is_phoenix_pd'), 'aircraft', ['is_phoenix_pd'], unique=False)
    op.create_index(op.f('ix_aircraft_registration'), 'aircraft', ['registration'], unique=True)
    op.alter_column('constitutional_analyses', 'systematic_surveillance_detected',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('constitutional_analyses', 'surveillance_intensity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('constitutional_analyses', 'discriminatory_impact_detected',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('constitutional_analyses', 'disparate_impact_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('constitutional_analyses', 'total_surveillance_events',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('constitutional_analyses', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('constitutional_analyses', 'peer_reviewed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_constitutional_analyses_date_range_end'), 'constitutional_analyses', ['date_range_end'], unique=False)
    op.create_index(op.f('ix_constitutional_analyses_date_range_start'), 'constitutional_analyses', ['date_range_start'], unique=False)
    op.create_index(op.f('ix_constitutional_analyses_discriminatory_impact_detected'), 'constitutional_analyses', ['discriminatory_impact_detected'], unique=False)
    op.create_index(op.f('ix_constitutional_analyses_id'), 'constitutional_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_constitutional_analyses_legal_document_id'), 'constitutional_analyses', ['legal_document_id'], unique=False)
    op.create_index(op.f('ix_constitutional_analyses_surveillance_intensity_score'), 'constitutional_analyses', ['surveillance_intensity_score'], unique=False)
    op.create_index(op.f('ix_constitutional_analyses_systematic_surveillance_detected'), 'constitutional_analyses', ['systematic_surveillance_detected'], unique=False)
    op.alter_column('flight_logs', 'flight_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('flight_logs', 'callsign',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_constraint('flight_logs_flight_id_key', 'flight_logs', type_='unique')
    op.drop_index('idx_flight_logs_callsign', table_name='flight_logs')
    op.drop_index('idx_flight_logs_created', table_name='flight_logs')
    op.drop_index('idx_flight_logs_data_source', table_name='flight_logs')
    op.drop_index('idx_flight_logs_flight_id', table_name='flight_logs')
    op.create_index(op.f('ix_flight_logs_aircraft_id'), 'flight_logs', ['aircraft_id'], unique=False)
    op.create_index(op.f('ix_flight_logs_arrival_time'), 'flight_logs', ['arrival_time'], unique=False)
    op.create_index(op.f('ix_flight_logs_callsign'), 'flight_logs', ['callsign'], unique=False)
    op.create_index(op.f('ix_flight_logs_created_at'), 'flight_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_flight_logs_data_source'), 'flight_logs', ['data_source'], unique=False)
    op.create_index(op.f('ix_flight_logs_departure_time'), 'flight_logs', ['departure_time'], unique=False)
    op.create_index(op.f('ix_flight_logs_flight_id'), 'flight_logs', ['flight_id'], unique=True)
    op.create_index(op.f('ix_flight_logs_id'), 'flight_logs', ['id'], unique=False)
    op.alter_column('flight_positions', 'is_hovering',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('flight_positions', 'is_circling',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_positions_flight_log', table_name='flight_positions')
    op.drop_index('idx_positions_neighborhood', table_name='flight_positions')
    op.create_index(op.f('ix_flight_positions_aircraft_id'), 'flight_positions', ['aircraft_id'], unique=False)
    op.create_index(op.f('ix_flight_positions_flight_log_id'), 'flight_positions', ['flight_log_id'], unique=False)
    op.create_index(op.f('ix_flight_positions_id'), 'flight_positions', ['id'], unique=False)
    op.create_index(op.f('ix_flight_positions_is_hovering'), 'flight_positions', ['is_hovering'], unique=False)
    op.create_index(op.f('ix_flight_positions_latitude'), 'flight_positions', ['latitude'], unique=False)
    op.create_index(op.f('ix_flight_positions_longitude'), 'flight_positions', ['longitude'], unique=False)
    op.create_index(op.f('ix_flight_positions_neighborhood'), 'flight_positions', ['neighborhood'], unique=False)
    op.create_index(op.f('ix_flight_positions_over_private_property'), 'flight_positions', ['over_private_property'], unique=False)
    op.create_index(op.f('ix_flight_positions_timestamp'), 'flight_positions', ['timestamp'], unique=False)
    op.alter_column('legal_documents', 'aircraft_filter',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('legal_documents', 'export_format',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=True)
    op.alter_column('legal_documents', 'include_maps',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('legal_documents', 'include_raw_data',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('legal_documents', 'generation_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('legal_documents', 'download_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_legal_documents_created_at'), 'legal_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_legal_documents_date_range_end'), 'legal_documents', ['date_range_end'], unique=False)
    op.create_index(op.f('ix_legal_documents_date_range_start'), 'legal_documents', ['date_range_start'], unique=False)
    op.create_index(op.f('ix_legal_documents_document_type'), 'legal_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_legal_documents_generated_at'), 'legal_documents', ['generated_at'], unique=False)
    op.create_index(op.f('ix_legal_documents_generation_status'), 'legal_documents', ['generation_status'], unique=False)
    op.create_index(op.f('ix_legal_documents_id'), 'legal_documents', ['id'], unique=False)
    op.create_index(op.f('ix_legal_documents_title'), 'legal_documents', ['title'], unique=False)
    op.alter_column('legal_precedents', 'surveillance_relevance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('legal_precedents', 'binding_precedent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('legal_precedents', 'citation_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_precedents_case_name', table_name='legal_precedents')
    op.drop_index('idx_precedents_citation', table_name='legal_precedents')
    op.create_index(op.f('ix_legal_precedents_binding_precedent'), 'legal_precedents', ['binding_precedent'], unique=False)
    op.create_index(op.f('ix_legal_precedents_case_name'), 'legal_precedents', ['case_name'], unique=False)
    op.create_index(op.f('ix_legal_precedents_case_type'), 'legal_precedents', ['case_type'], unique=False)
    op.create_index(op.f('ix_legal_precedents_citation'), 'legal_precedents', ['citation'], unique=False)
    op.create_index(op.f('ix_legal_precedents_decision_date'), 'legal_precedents', ['decision_date'], unique=False)
    op.create_index(op.f('ix_legal_precedents_id'), 'legal_precedents', ['id'], unique=False)
    op.create_index(op.f('ix_legal_precedents_jurisdiction'), 'legal_precedents', ['jurisdiction'], unique=False)
    op.create_index(op.f('ix_legal_precedents_surveillance_relevance'), 'legal_precedents', ['surveillance_relevance'], unique=False)
    op.alter_column('task_events', 'severity',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_task_events_created', table_name='task_events')
    op.drop_index('idx_task_events_event_type', table_name='task_events')
    op.drop_index('idx_task_events_task_id', table_name='task_events')
    op.drop_index('idx_task_events_task_name', table_name='task_events')
    op.create_index(op.f('ix_task_events_created_at'), 'task_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_events_event_type'), 'task_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_task_events_id'), 'task_events', ['id'], unique=False)
    op.create_index(op.f('ix_task_events_task_id'), 'task_events', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_events_task_name'), 'task_events', ['task_name'], unique=False)
    op.alter_column('task_history', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_task_history_created', table_name='task_history')
    op.drop_index('idx_task_history_status', table_name='task_history')
    op.drop_index('idx_task_history_task_id', table_name='task_history')
    op.drop_index('idx_task_history_task_name', table_name='task_history')
    op.drop_constraint('task_history_task_id_key', 'task_history', type_='unique')
    op.create_index(op.f('ix_task_history_id'), 'task_history', ['id'], unique=False)
    op.create_index(op.f('ix_task_history_status'), 'task_history', ['status'], unique=False)
    op.create_index(op.f('ix_task_history_task_id'), 'task_history', ['task_id'], unique=True)
    op.create_index(op.f('ix_task_history_task_name'), 'task_history', ['task_name'], unique=False)
    op.alter_column('task_metrics', 'total_runs',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('task_metrics', 'successful_runs',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('task_metrics', 'failed_runs',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('task_metrics', 'retry_runs',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('task_metrics', 'total_records_processed',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('task_metrics', 'total_credits_used',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_task_metrics_task_name', table_name='task_metrics')
    op.drop_constraint('task_metrics_task_name_key', 'task_metrics', type_='unique')
    op.create_index(op.f('ix_task_metrics_id'), 'task_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_task_metrics_task_name'), 'task_metrics', ['task_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_metrics_task_name'), table_name='task_metrics')
    op.drop_index(op.f('ix_task_metrics_id'), table_name='task_metrics')
    op.create_unique_constraint('task_metrics_task_name_key', 'task_metrics', ['task_name'])
    op.create_index('idx_task_metrics_task_name', 'task_metrics', ['task_name'], unique=False)
    op.alter_column('task_metrics', 'total_credits_used',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('task_metrics', 'total_records_processed',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('task_metrics', 'retry_runs',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('task_metrics', 'failed_runs',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('task_metrics', 'successful_runs',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('task_metrics', 'total_runs',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.drop_index(op.f('ix_task_history_task_name'), table_name='task_history')
    op.drop_index(op.f('ix_task_history_task_id'), table_name='task_history')
    op.drop_index(op.f('ix_task_history_status'), table_name='task_history')
    op.drop_index(op.f('ix_task_history_id'), table_name='task_history')
    op.create_unique_constraint('task_history_task_id_key', 'task_history', ['task_id'])
    op.create_index('idx_task_history_task_name', 'task_history', ['task_name'], unique=False)
    op.create_index('idx_task_history_task_id', 'task_history', ['task_id'], unique=False)
    op.create_index('idx_task_history_status', 'task_history', ['status'], unique=False)
    op.create_index('idx_task_history_created', 'task_history', ['created_at'], unique=False)
    op.alter_column('task_history', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.drop_index(op.f('ix_task_events_task_name'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_task_id'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_id'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_event_type'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_created_at'), table_name='task_events')
    op.create_index('idx_task_events_task_name', 'task_events', ['task_name'], unique=False)
    op.create_index('idx_task_events_task_id', 'task_events', ['task_id'], unique=False)
    op.create_index('idx_task_events_event_type', 'task_events', ['event_type'], unique=False)
    op.create_index('idx_task_events_created', 'task_events', ['created_at'], unique=False)
    op.alter_column('task_events', 'severity',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.drop_index(op.f('ix_legal_precedents_surveillance_relevance'), table_name='legal_precedents')
    op.drop_index(op.f('ix_legal_precedents_jurisdiction'), table_name='legal_precedents')
    op.drop_index(op.f('ix_legal_precedents_id'), table_name='legal_precedents')
    op.drop_index(op.f('ix_legal_precedents_decision_date'), table_name='legal_precedents')
    op.drop_index(op.f('ix_legal_precedents_citation'), table_name='legal_precedents')
    op.drop_index(op.f('ix_legal_precedents_case_type'), table_name='legal_precedents')
    op.drop_index(op.f('ix_legal_precedents_case_name'), table_name='legal_precedents')
    op.drop_index(op.f('ix_legal_precedents_binding_precedent'), table_name='legal_precedents')
    op.create_index('idx_precedents_citation', 'legal_precedents', ['citation'], unique=False)
    op.create_index('idx_precedents_case_name', 'legal_precedents', ['case_name'], unique=False)
    op.alter_column('legal_precedents', 'citation_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('legal_precedents', 'binding_precedent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('legal_precedents', 'surveillance_relevance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=True)
    op.drop_index(op.f('ix_legal_documents_title'), table_name='legal_documents')
    op.drop_index(op.f('ix_legal_documents_id'), table_name='legal_documents')
    op.drop_index(op.f('ix_legal_documents_generation_status'), table_name='legal_documents')
    op.drop_index(op.f('ix_legal_documents_generated_at'), table_name='legal_documents')
    op.drop_index(op.f('ix_legal_documents_document_type'), table_name='legal_documents')
    op.drop_index(op.f('ix_legal_documents_date_range_start'), table_name='legal_documents')
    op.drop_index(op.f('ix_legal_documents_date_range_end'), table_name='legal_documents')
    op.drop_index(op.f('ix_legal_documents_created_at'), table_name='legal_documents')
    op.alter_column('legal_documents', 'download_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('legal_documents', 'generation_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=True)
    op.alter_column('legal_documents', 'include_raw_data',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('legal_documents', 'include_maps',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('legal_documents', 'export_format',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'pdf'::character varying"),
               existing_nullable=True)
    op.alter_column('legal_documents', 'aircraft_filter',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.drop_index(op.f('ix_flight_positions_timestamp'), table_name='flight_positions')
    op.drop_index(op.f('ix_flight_positions_over_private_property'), table_name='flight_positions')
    op.drop_index(op.f('ix_flight_positions_neighborhood'), table_name='flight_positions')
    op.drop_index(op.f('ix_flight_positions_longitude'), table_name='flight_positions')
    op.drop_index(op.f('ix_flight_positions_latitude'), table_name='flight_positions')
    op.drop_index(op.f('ix_flight_positions_is_hovering'), table_name='flight_positions')
    op.drop_index(op.f('ix_flight_positions_id'), table_name='flight_positions')
    op.drop_index(op.f('ix_flight_positions_flight_log_id'), table_name='flight_positions')
    op.drop_index(op.f('ix_flight_positions_aircraft_id'), table_name='flight_positions')
    op.create_index('idx_positions_neighborhood', 'flight_positions', ['neighborhood'], unique=False)
    op.create_index('idx_positions_flight_log', 'flight_positions', ['flight_log_id'], unique=False)
    op.alter_column('flight_positions', 'is_circling',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('flight_positions', 'is_hovering',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.drop_index(op.f('ix_flight_logs_id'), table_name='flight_logs')
    op.drop_index(op.f('ix_flight_logs_flight_id'), table_name='flight_logs')
    op.drop_index(op.f('ix_flight_logs_departure_time'), table_name='flight_logs')
    op.drop_index(op.f('ix_flight_logs_data_source'), table_name='flight_logs')
    op.drop_index(op.f('ix_flight_logs_created_at'), table_name='flight_logs')
    op.drop_index(op.f('ix_flight_logs_callsign'), table_name='flight_logs')
    op.drop_index(op.f('ix_flight_logs_arrival_time'), table_name='flight_logs')
    op.drop_index(op.f('ix_flight_logs_aircraft_id'), table_name='flight_logs')
    op.create_index('idx_flight_logs_flight_id', 'flight_logs', ['flight_id'], unique=False)
    op.create_index('idx_flight_logs_data_source', 'flight_logs', ['data_source'], unique=False)
    op.create_index('idx_flight_logs_created', 'flight_logs', ['created_at'], unique=False)
    op.create_index('idx_flight_logs_callsign', 'flight_logs', ['callsign'], unique=False)
    op.create_unique_constraint('flight_logs_flight_id_key', 'flight_logs', ['flight_id'])
    op.alter_column('flight_logs', 'callsign',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('flight_logs', 'flight_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_constitutional_analyses_systematic_surveillance_detected'), table_name='constitutional_analyses')
    op.drop_index(op.f('ix_constitutional_analyses_surveillance_intensity_score'), table_name='constitutional_analyses')
    op.drop_index(op.f('ix_constitutional_analyses_legal_document_id'), table_name='constitutional_analyses')
    op.drop_index(op.f('ix_constitutional_analyses_id'), table_name='constitutional_analyses')
    op.drop_index(op.f('ix_constitutional_analyses_discriminatory_impact_detected'), table_name='constitutional_analyses')
    op.drop_index(op.f('ix_constitutional_analyses_date_range_start'), table_name='constitutional_analyses')
    op.drop_index(op.f('ix_constitutional_analyses_date_range_end'), table_name='constitutional_analyses')
    op.alter_column('constitutional_analyses', 'peer_reviewed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('constitutional_analyses', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=True)
    op.alter_column('constitutional_analyses', 'total_surveillance_events',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('constitutional_analyses', 'disparate_impact_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=True)
    op.alter_column('constitutional_analyses', 'discriminatory_impact_detected',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('constitutional_analyses', 'surveillance_intensity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=True)
    op.alter_column('constitutional_analyses', 'systematic_surveillance_detected',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.drop_index(op.f('ix_aircraft_registration'), table_name='aircraft')
    op.drop_index(op.f('ix_aircraft_is_phoenix_pd'), table_name='aircraft')
    op.drop_index(op.f('ix_aircraft_id'), table_name='aircraft')
    op.drop_index(op.f('ix_aircraft_icao_code'), table_name='aircraft')
    op.create_index('idx_aircraft_registration', 'aircraft', ['registration'], unique=False)
    op.create_index('idx_aircraft_phoenix_pd', 'aircraft', ['is_phoenix_pd'], unique=False)
    op.create_index('idx_aircraft_icao', 'aircraft', ['icao_code'], unique=False)
    op.create_unique_constraint('aircraft_registration_key', 'aircraft', ['registration'])
    op.create_unique_constraint('aircraft_icao_code_key', 'aircraft', ['icao_code'])
    op.alter_column('aircraft', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('aircraft', 'hourly_operating_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('2160.0'),
               existing_nullable=True)
    op.alter_column('aircraft', 'has_loudspeaker',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('aircraft', 'has_spotlight',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('aircraft', 'has_flir',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('aircraft', 'is_phoenix_pd',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.create_table('system_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('level', postgresql.ENUM('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='loglevel'), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('FLIGHT_DOWNLOAD', 'DATA_PARSING', 'FR24_API', 'DATABASE', 'ANALYSIS', 'CELERY_TASK', 'DATA_INTEGRITY', 'BACKUP', 'AUTHENTICATION', 'SYSTEM', 'ANOMALY', name='logcategory'), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('flight_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('registration', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('error_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('error_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('context_metadata', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='system_logs_pkey')
    )
    op.create_index('ix_system_logs_source', 'system_logs', ['source'], unique=False)
    op.create_index('ix_system_logs_registration', 'system_logs', ['registration'], unique=False)
    op.create_index('ix_system_logs_level', 'system_logs', ['level'], unique=False)
    op.create_index('ix_system_logs_id', 'system_logs', ['id'], unique=False)
    op.create_index('ix_system_logs_flight_id', 'system_logs', ['flight_id'], unique=False)
    op.create_index('ix_system_logs_created_at', 'system_logs', ['created_at'], unique=False)
    op.create_index('ix_system_logs_category', 'system_logs', ['category'], unique=False)
    op.create_index('idx_logs_level_category', 'system_logs', ['level', 'category'], unique=False)
    op.create_index('idx_logs_created_level', 'system_logs', ['created_at', 'level'], unique=False)
    op.create_index('idx_logs_category_created', 'system_logs', ['category', 'created_at'], unique=False)
    # ### end Alembic commands ###
