"""Add system_issues table for error monitoring

Revision ID: 7dcc4653a86a
Revises: 376fc70067b9
Create Date: 2025-10-13 00:09:25.630203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7dcc4653a86a'
down_revision: Union[str, None] = '376fc70067b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_logs_category_created', table_name='system_logs')
    op.drop_index('idx_logs_created_level', table_name='system_logs')
    op.drop_index('idx_logs_level_category', table_name='system_logs')
    op.drop_index('ix_system_logs_category', table_name='system_logs')
    op.drop_index('ix_system_logs_created_at', table_name='system_logs')
    op.drop_index('ix_system_logs_flight_id', table_name='system_logs')
    op.drop_index('ix_system_logs_id', table_name='system_logs')
    op.drop_index('ix_system_logs_level', table_name='system_logs')
    op.drop_index('ix_system_logs_registration', table_name='system_logs')
    op.drop_index('ix_system_logs_source', table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index('ix_system_issues_component', table_name='system_issues')
    op.drop_index('ix_system_issues_error_signature', table_name='system_issues')
    op.drop_index('ix_system_issues_id', table_name='system_issues')
    op.drop_index('ix_system_issues_is_resolved', table_name='system_issues')
    op.drop_index('ix_system_issues_issue_type', table_name='system_issues')
    op.drop_table('system_issues')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_issues',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('issue_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('component', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('error_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('stack_trace', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('first_seen', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_seen', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('occurrence_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_resolved', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('resolved_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('resolution_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_signature', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='system_issues_pkey')
    )
    op.create_index('ix_system_issues_issue_type', 'system_issues', ['issue_type'], unique=False)
    op.create_index('ix_system_issues_is_resolved', 'system_issues', ['is_resolved'], unique=False)
    op.create_index('ix_system_issues_id', 'system_issues', ['id'], unique=False)
    op.create_index('ix_system_issues_error_signature', 'system_issues', ['error_signature'], unique=False)
    op.create_index('ix_system_issues_component', 'system_issues', ['component'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('level', postgresql.ENUM('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='loglevel'), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('FLIGHT_DOWNLOAD', 'DATA_PARSING', 'FR24_API', 'DATABASE', 'ANALYSIS', 'CELERY_TASK', 'DATA_INTEGRITY', 'BACKUP', 'AUTHENTICATION', 'SYSTEM', 'ANOMALY', name='logcategory'), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('flight_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('registration', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('error_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('error_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('context_metadata', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='system_logs_pkey')
    )
    op.create_index('ix_system_logs_source', 'system_logs', ['source'], unique=False)
    op.create_index('ix_system_logs_registration', 'system_logs', ['registration'], unique=False)
    op.create_index('ix_system_logs_level', 'system_logs', ['level'], unique=False)
    op.create_index('ix_system_logs_id', 'system_logs', ['id'], unique=False)
    op.create_index('ix_system_logs_flight_id', 'system_logs', ['flight_id'], unique=False)
    op.create_index('ix_system_logs_created_at', 'system_logs', ['created_at'], unique=False)
    op.create_index('ix_system_logs_category', 'system_logs', ['category'], unique=False)
    op.create_index('idx_logs_level_category', 'system_logs', ['level', 'category'], unique=False)
    op.create_index('idx_logs_created_level', 'system_logs', ['created_at', 'level'], unique=False)
    op.create_index('idx_logs_category_created', 'system_logs', ['category', 'created_at'], unique=False)
    # ### end Alembic commands ###
