"""sync_flight_positions_indexes_with_postgis_model

Revision ID: ccca6db6c0ac
Revises: e4575341c2cd
Create Date: 2025-10-13 03:43:02.907310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ccca6db6c0ac"
down_revision: Union[str, None] = "e4575341c2cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: spatial_ref_sys is a PostGIS system table - don't drop it
    # op.drop_table('spatial_ref_sys')  # REMOVED - PostGIS system table
    op.drop_index("idx_positions_privacy", table_name="flight_positions")
    op.drop_index("idx_positions_time_aircraft", table_name="flight_positions")
    op.drop_index("ix_flight_positions_aircraft_id", table_name="flight_positions")
    op.drop_index("ix_flight_positions_is_hovering", table_name="flight_positions")
    op.drop_index("ix_flight_positions_latitude", table_name="flight_positions")
    op.drop_index("ix_flight_positions_longitude", table_name="flight_positions")
    op.drop_index("ix_flight_positions_neighborhood", table_name="flight_positions")
    op.drop_index(
        "ix_flight_positions_over_private_property", table_name="flight_positions"
    )
    op.drop_index("idx_positions_location", table_name="flight_positions")
    op.create_index(
        "idx_positions_location",
        "flight_positions",
        ["location"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        "idx_positions_flight_timestamp",
        "flight_positions",
        ["flight_log_id", "timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_positions_flight_timestamp", table_name="flight_positions")
    op.drop_index(
        "idx_positions_location", table_name="flight_positions", postgresql_using="gist"
    )
    op.create_index(
        "idx_positions_location",
        "flight_positions",
        ["latitude", "longitude"],
        unique=False,
    )
    op.create_index(
        "ix_flight_positions_over_private_property",
        "flight_positions",
        ["over_private_property"],
        unique=False,
    )
    op.create_index(
        "ix_flight_positions_neighborhood",
        "flight_positions",
        ["neighborhood"],
        unique=False,
    )
    op.create_index(
        "ix_flight_positions_longitude", "flight_positions", ["longitude"], unique=False
    )
    op.create_index(
        "ix_flight_positions_latitude", "flight_positions", ["latitude"], unique=False
    )
    op.create_index(
        "ix_flight_positions_is_hovering",
        "flight_positions",
        ["is_hovering"],
        unique=False,
    )
    op.create_index(
        "ix_flight_positions_aircraft_id",
        "flight_positions",
        ["aircraft_id"],
        unique=False,
    )
    op.create_index(
        "idx_positions_time_aircraft",
        "flight_positions",
        ["timestamp", "aircraft_id"],
        unique=False,
    )
    op.create_index(
        "idx_positions_privacy",
        "flight_positions",
        ["over_private_property", "altitude_privacy_concern"],
        unique=False,
    )
    # NOTE: spatial_ref_sys is a PostGIS system table - don't recreate it
    # Removed spatial_ref_sys table recreation
    # ### end Alembic commands ###
