"""Add system_logs table for error tracking

Revision ID: d20f368f5243
Revises: 4a23c3c2fdc4
Create Date: 2025-09-27 23:02:40.597702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd20f368f5243'
down_revision: Union[str, None] = '4a23c3c2fdc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
