"""baseline schema from models

Revision ID: f6127cc4f43a
Revises: 
Create Date: 2026-06-13 05:38:02.696714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f6127cc4f43a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # PostGIS is required for the flight_positions.location geography column.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.create_table(
        "aircraft",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("registration", sa.String(length=10), nullable=False),
        sa.Column("icao_code", sa.String(length=6), nullable=True),
        sa.Column("make", sa.String(length=50), nullable=True),
        sa.Column("model", sa.String(length=50), nullable=True),
        sa.Column("year_manufactured", sa.Integer(), nullable=True),
        sa.Column("operator", sa.String(length=100), nullable=True),
        sa.Column("is_phoenix_pd", sa.Boolean(), nullable=True),
        sa.Column("unit_designation", sa.String(length=20), nullable=True),
        sa.Column("has_flir", sa.Boolean(), nullable=True),
        sa.Column("has_spotlight", sa.Boolean(), nullable=True),
        sa.Column("has_loudspeaker", sa.Boolean(), nullable=True),
        sa.Column("max_flight_time_minutes", sa.Integer(), nullable=True),
        sa.Column("hourly_operating_cost", sa.Float(), nullable=True),
        sa.Column("purchase_cost", sa.Float(), nullable=True),
        sa.Column("annual_maintenance_cost", sa.Float(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_aircraft_icao_code"), "aircraft", ["icao_code"], unique=True
    )
    op.create_index(op.f("ix_aircraft_id"), "aircraft", ["id"], unique=False)
    op.create_index(
        op.f("ix_aircraft_is_phoenix_pd"), "aircraft", ["is_phoenix_pd"], unique=False
    )
    op.create_index(
        op.f("ix_aircraft_registration"), "aircraft", ["registration"], unique=True
    )
    op.create_table(
        "flight_discoveries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fr24_id", sa.String(length=20), nullable=False),
        sa.Column("registration", sa.String(length=10), nullable=False),
        sa.Column("callsign", sa.String(length=10), nullable=True),
        sa.Column("aircraft_type", sa.String(length=10), nullable=True),
        sa.Column("hex_code", sa.String(length=10), nullable=True),
        sa.Column("departure_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("arrival_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("origin_airport", sa.String(length=10), nullable=True),
        sa.Column("destination_airport", sa.String(length=10), nullable=True),
        sa.Column("flight_duration_minutes", sa.Float(), nullable=True),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "discovered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("track_downloaded", sa.Boolean(), nullable=True),
        sa.Column(
            "track_download_attempted_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("track_download_error", sa.Text(), nullable=True),
        sa.Column("positions_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_flight_discoveries_departure_time"),
        "flight_discoveries",
        ["departure_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flight_discoveries_fr24_id"),
        "flight_discoveries",
        ["fr24_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_flight_discoveries_id"), "flight_discoveries", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_flight_discoveries_registration"),
        "flight_discoveries",
        ["registration"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flight_discoveries_track_downloaded"),
        "flight_discoveries",
        ["track_downloaded"],
        unique=False,
    )
    op.create_table(
        "legal_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("document_type", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("date_range_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("date_range_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("geographic_area", sa.String(length=200), nullable=True),
        sa.Column("aircraft_filter", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("incident_filter", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.Column(
            "analysis_parameters",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("export_format", sa.String(length=10), nullable=True),
        sa.Column("include_maps", sa.Boolean(), nullable=True),
        sa.Column("include_raw_data", sa.Boolean(), nullable=True),
        sa.Column("attorney_notes", sa.Text(), nullable=True),
        sa.Column("executive_summary", sa.Text(), nullable=True),
        sa.Column("findings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "recommendations", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("file_path", sa.String(length=500), nullable=True),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("generation_status", sa.String(length=20), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("generation_duration_seconds", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("download_count", sa.Integer(), nullable=True),
        sa.Column("last_downloaded", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_legal_docs_date_range",
        "legal_documents",
        ["date_range_start", "date_range_end"],
        unique=False,
    )
    op.create_index(
        "idx_legal_docs_generated",
        "legal_documents",
        ["generated_at", "download_count"],
        unique=False,
    )
    op.create_index(
        "idx_legal_docs_type_status",
        "legal_documents",
        ["document_type", "generation_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_documents_created_at"),
        "legal_documents",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_documents_date_range_end"),
        "legal_documents",
        ["date_range_end"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_documents_date_range_start"),
        "legal_documents",
        ["date_range_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_documents_document_type"),
        "legal_documents",
        ["document_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_documents_generated_at"),
        "legal_documents",
        ["generated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_documents_generation_status"),
        "legal_documents",
        ["generation_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_documents_id"), "legal_documents", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_legal_documents_title"), "legal_documents", ["title"], unique=False
    )
    op.create_table(
        "legal_precedents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_name", sa.String(length=200), nullable=False),
        sa.Column("citation", sa.String(length=100), nullable=False),
        sa.Column("court", sa.String(length=100), nullable=False),
        sa.Column("decision_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("case_summary", sa.Text(), nullable=True),
        sa.Column("holding", sa.Text(), nullable=False),
        sa.Column("legal_principle", sa.Text(), nullable=True),
        sa.Column("surveillance_relevance", sa.Float(), nullable=True),
        sa.Column("fourth_amendment_analysis", sa.Text(), nullable=True),
        sa.Column("privacy_analysis", sa.Text(), nullable=True),
        sa.Column("case_type", sa.String(length=50), nullable=True),
        sa.Column("jurisdiction", sa.String(length=50), nullable=True),
        sa.Column("binding_precedent", sa.Boolean(), nullable=True),
        sa.Column("key_facts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "distinguishing_factors",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "supporting_authority",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("citation_count", sa.Integer(), nullable=True),
        sa.Column("last_cited", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("added_by", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_precedents_court_date",
        "legal_precedents",
        ["court", "decision_date"],
        unique=False,
    )
    op.create_index(
        "idx_precedents_relevance",
        "legal_precedents",
        ["surveillance_relevance", "binding_precedent"],
        unique=False,
    )
    op.create_index(
        "idx_precedents_type_jurisdiction",
        "legal_precedents",
        ["case_type", "jurisdiction"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_precedents_binding_precedent"),
        "legal_precedents",
        ["binding_precedent"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_precedents_case_name"),
        "legal_precedents",
        ["case_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_precedents_case_type"),
        "legal_precedents",
        ["case_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_precedents_citation"),
        "legal_precedents",
        ["citation"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_precedents_decision_date"),
        "legal_precedents",
        ["decision_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_precedents_id"), "legal_precedents", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_legal_precedents_jurisdiction"),
        "legal_precedents",
        ["jurisdiction"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_precedents_surveillance_relevance"),
        "legal_precedents",
        ["surveillance_relevance"],
        unique=False,
    )
    op.create_table(
        "radio_archives",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=512), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("feed_id", sa.String(length=20), nullable=True),
        sa.Column("feed_name", sa.String(length=100), nullable=True),
        sa.Column("recording_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recording_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "downloaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("download_source", sa.String(length=100), nullable=True),
        sa.Column("audio_format", sa.String(length=20), nullable=True),
        sa.Column("sample_rate", sa.Integer(), nullable=True),
        sa.Column("bitrate", sa.Integer(), nullable=True),
        sa.Column("transcribed", sa.Boolean(), nullable=True),
        sa.Column("analyzed", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_radio_archives_feed_time",
        "radio_archives",
        ["feed_id", "recording_start"],
        unique=False,
    )
    op.create_index(
        "idx_radio_archives_status",
        "radio_archives",
        ["transcribed", "analyzed"],
        unique=False,
    )
    op.create_index(
        "idx_radio_archives_time_range",
        "radio_archives",
        ["recording_start", "recording_end"],
        unique=False,
    )
    op.create_index(
        op.f("ix_radio_archives_analyzed"), "radio_archives", ["analyzed"], unique=False
    )
    op.create_index(
        op.f("ix_radio_archives_created_at"),
        "radio_archives",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_radio_archives_downloaded_at"),
        "radio_archives",
        ["downloaded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_radio_archives_feed_id"), "radio_archives", ["feed_id"], unique=False
    )
    op.create_index(
        op.f("ix_radio_archives_filename"), "radio_archives", ["filename"], unique=True
    )
    op.create_index(
        op.f("ix_radio_archives_id"), "radio_archives", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_radio_archives_recording_end"),
        "radio_archives",
        ["recording_end"],
        unique=False,
    )
    op.create_index(
        op.f("ix_radio_archives_recording_start"),
        "radio_archives",
        ["recording_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_radio_archives_transcribed"),
        "radio_archives",
        ["transcribed"],
        unique=False,
    )
    op.create_table(
        "system_issues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("issue_type", sa.String(length=50), nullable=False),
        sa.Column("component", sa.String(length=100), nullable=False),
        sa.Column("error_name", sa.String(length=200), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("stack_trace", sa.Text(), nullable=True),
        sa.Column("context", sa.JSON(), nullable=True),
        sa.Column(
            "first_seen",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("is_resolved", sa.Boolean(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.String(length=100), nullable=True),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.Column("priority", sa.String(length=20), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("error_signature", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_issues_component"), "system_issues", ["component"], unique=False
    )
    op.create_index(
        op.f("ix_system_issues_error_signature"),
        "system_issues",
        ["error_signature"],
        unique=True,
    )
    op.create_index(op.f("ix_system_issues_id"), "system_issues", ["id"], unique=False)
    op.create_index(
        op.f("ix_system_issues_is_resolved"),
        "system_issues",
        ["is_resolved"],
        unique=False,
    )
    op.create_index(
        op.f("ix_system_issues_issue_type"),
        "system_issues",
        ["issue_type"],
        unique=False,
    )
    op.create_table(
        "system_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL", name="loglevel"),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum(
                "FLIGHT_DOWNLOAD",
                "DATA_PARSING",
                "FR24_API",
                "DATABASE",
                "ANALYSIS",
                "CELERY_TASK",
                "DATA_INTEGRITY",
                "BACKUP",
                "AUTHENTICATION",
                "SYSTEM",
                "ANOMALY",
                name="logcategory",
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("task_id", sa.String(length=100), nullable=True),
        sa.Column("flight_id", sa.String(length=100), nullable=True),
        sa.Column("registration", sa.String(length=20), nullable=True),
        sa.Column("error_type", sa.String(length=100), nullable=True),
        sa.Column("error_details", sa.Text(), nullable=True),
        sa.Column("context_metadata", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_logs_category_created",
        "system_logs",
        ["category", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_logs_created_level", "system_logs", ["created_at", "level"], unique=False
    )
    op.create_index(
        "idx_logs_level_category", "system_logs", ["level", "category"], unique=False
    )
    op.create_index(
        op.f("ix_system_logs_category"), "system_logs", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_system_logs_created_at"), "system_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_system_logs_flight_id"), "system_logs", ["flight_id"], unique=False
    )
    op.create_index(op.f("ix_system_logs_id"), "system_logs", ["id"], unique=False)
    op.create_index(
        op.f("ix_system_logs_level"), "system_logs", ["level"], unique=False
    )
    op.create_index(
        op.f("ix_system_logs_registration"),
        "system_logs",
        ["registration"],
        unique=False,
    )
    op.create_index(
        op.f("ix_system_logs_source"), "system_logs", ["source"], unique=False
    )
    op.create_table(
        "task_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.String(length=255), nullable=True),
        sa.Column("task_name", sa.String(length=255), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=True),
        sa.Column("severity", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_task_events_created_at"), "task_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_task_events_event_type"), "task_events", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_task_events_id"), "task_events", ["id"], unique=False)
    op.create_index(
        op.f("ix_task_events_task_id"), "task_events", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_events_task_name"), "task_events", ["task_name"], unique=False
    )
    op.create_table(
        "task_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.String(length=255), nullable=True),
        sa.Column("task_name", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("runtime_seconds", sa.Float(), nullable=True),
        sa.Column("args", sa.JSON(), nullable=True),
        sa.Column("kwargs", sa.JSON(), nullable=True),
        sa.Column("queue", sa.String(length=100), nullable=True),
        sa.Column("worker", sa.String(length=255), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("traceback", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column("credits_used", sa.Integer(), nullable=True),
        sa.Column("records_processed", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_history_id"), "task_history", ["id"], unique=False)
    op.create_index(
        op.f("ix_task_history_status"), "task_history", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_task_history_task_id"), "task_history", ["task_id"], unique=True
    )
    op.create_index(
        op.f("ix_task_history_task_name"), "task_history", ["task_name"], unique=False
    )
    op.create_table(
        "task_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_name", sa.String(length=255), nullable=True),
        sa.Column("total_runs", sa.Integer(), nullable=True),
        sa.Column("successful_runs", sa.Integer(), nullable=True),
        sa.Column("failed_runs", sa.Integer(), nullable=True),
        sa.Column("retry_runs", sa.Integer(), nullable=True),
        sa.Column("avg_runtime_seconds", sa.Float(), nullable=True),
        sa.Column("max_runtime_seconds", sa.Float(), nullable=True),
        sa.Column("min_runtime_seconds", sa.Float(), nullable=True),
        sa.Column("total_records_processed", sa.Integer(), nullable=True),
        sa.Column("total_credits_used", sa.Integer(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_metrics_id"), "task_metrics", ["id"], unique=False)
    op.create_index(
        op.f("ix_task_metrics_task_name"), "task_metrics", ["task_name"], unique=True
    )
    op.create_table(
        "constitutional_analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_name", sa.String(length=200), nullable=False),
        sa.Column("date_range_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("date_range_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("geographic_scope", sa.String(length=200), nullable=True),
        sa.Column(
            "fourth_amendment_violations",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "privacy_expectation_analysis",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "surveillance_patterns",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("systematic_surveillance_detected", sa.Boolean(), nullable=True),
        sa.Column("surveillance_intensity_score", sa.Float(), nullable=True),
        sa.Column(
            "targeted_areas", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "applicable_precedents",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "precedent_violations",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("discriminatory_impact_detected", sa.Boolean(), nullable=True),
        sa.Column(
            "demographic_analysis",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("disparate_impact_score", sa.Float(), nullable=True),
        sa.Column("total_flights_analyzed", sa.Integer(), nullable=False),
        sa.Column("total_surveillance_events", sa.Integer(), nullable=True),
        sa.Column("average_surveillance_duration", sa.Float(), nullable=True),
        sa.Column("cost_of_surveillance", sa.Float(), nullable=True),
        sa.Column(
            "recommended_legal_actions",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "injunction_grounds", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "damages_analysis", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("methodology_notes", sa.Text(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("peer_reviewed", sa.Boolean(), nullable=True),
        sa.Column("reviewer_notes", sa.Text(), nullable=True),
        sa.Column("legal_document_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("analyst_name", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["legal_document_id"],
            ["legal_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_const_analysis_date_range",
        "constitutional_analyses",
        ["date_range_start", "date_range_end"],
        unique=False,
    )
    op.create_index(
        "idx_const_analysis_scores",
        "constitutional_analyses",
        ["surveillance_intensity_score", "confidence_score"],
        unique=False,
    )
    op.create_index(
        "idx_const_analysis_violations",
        "constitutional_analyses",
        ["systematic_surveillance_detected", "discriminatory_impact_detected"],
        unique=False,
    )
    op.create_index(
        op.f("ix_constitutional_analyses_date_range_end"),
        "constitutional_analyses",
        ["date_range_end"],
        unique=False,
    )
    op.create_index(
        op.f("ix_constitutional_analyses_date_range_start"),
        "constitutional_analyses",
        ["date_range_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_constitutional_analyses_discriminatory_impact_detected"),
        "constitutional_analyses",
        ["discriminatory_impact_detected"],
        unique=False,
    )
    op.create_index(
        op.f("ix_constitutional_analyses_id"),
        "constitutional_analyses",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_constitutional_analyses_legal_document_id"),
        "constitutional_analyses",
        ["legal_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_constitutional_analyses_surveillance_intensity_score"),
        "constitutional_analyses",
        ["surveillance_intensity_score"],
        unique=False,
    )
    op.create_index(
        op.f("ix_constitutional_analyses_systematic_surveillance_detected"),
        "constitutional_analyses",
        ["systematic_surveillance_detected"],
        unique=False,
    )
    op.create_table(
        "flight_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("aircraft_id", sa.Integer(), nullable=False),
        sa.Column("flight_id", sa.String(length=100), nullable=True),
        sa.Column("callsign", sa.String(length=20), nullable=True),
        sa.Column("departure_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("arrival_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("flight_duration_minutes", sa.Float(), nullable=True),
        sa.Column("departure_airport", sa.String(length=10), nullable=True),
        sa.Column("arrival_airport", sa.String(length=10), nullable=True),
        sa.Column("max_altitude_feet", sa.Integer(), nullable=True),
        sa.Column("min_altitude_feet", sa.Integer(), nullable=True),
        sa.Column("avg_altitude_feet", sa.Integer(), nullable=True),
        sa.Column("max_altitude_agl_feet", sa.Integer(), nullable=True),
        sa.Column("min_altitude_agl_feet", sa.Integer(), nullable=True),
        sa.Column("avg_altitude_agl_feet", sa.Integer(), nullable=True),
        sa.Column("estimated_cost", sa.Float(), nullable=True),
        sa.Column("fuel_consumed_gallons", sa.Float(), nullable=True),
        sa.Column("data_source", sa.String(length=50), nullable=True),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "area_coverage", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "hover_locations", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "low_altitude_segments",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "surveillance_types", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("pattern_notes", sa.Text(), nullable=True),
        sa.Column("surveillance_likelihood", sa.Float(), nullable=True),
        sa.Column("privacy_concern_level", sa.Integer(), nullable=True),
        sa.Column("legal_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["aircraft_id"],
            ["aircraft.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_flight_logs_aircraft_date",
        "flight_logs",
        ["aircraft_id", "departure_time"],
        unique=False,
    )
    op.create_index(
        "idx_flight_logs_surveillance",
        "flight_logs",
        ["surveillance_likelihood", "privacy_concern_level"],
        unique=False,
    )
    op.create_index(
        "idx_flight_logs_time_range",
        "flight_logs",
        ["departure_time", "arrival_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flight_logs_aircraft_id"), "flight_logs", ["aircraft_id"], unique=False
    )
    op.create_index(
        op.f("ix_flight_logs_arrival_time"),
        "flight_logs",
        ["arrival_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flight_logs_callsign"), "flight_logs", ["callsign"], unique=False
    )
    op.create_index(
        op.f("ix_flight_logs_created_at"), "flight_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_flight_logs_data_source"), "flight_logs", ["data_source"], unique=False
    )
    op.create_index(
        op.f("ix_flight_logs_departure_time"),
        "flight_logs",
        ["departure_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flight_logs_flight_id"), "flight_logs", ["flight_id"], unique=True
    )
    op.create_index(op.f("ix_flight_logs_id"), "flight_logs", ["id"], unique=False)
    op.create_table(
        "radio_transcriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("archive_id", sa.Integer(), nullable=False),
        sa.Column("full_text", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("model_name", sa.String(length=50), nullable=True),
        sa.Column("model_version", sa.String(length=50), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("no_speech_probability", sa.Float(), nullable=True),
        sa.Column(
            "transcribed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("transcription_time_seconds", sa.Float(), nullable=True),
        sa.Column("worker_hostname", sa.String(length=100), nullable=True),
        sa.Column("detected_language_probability", sa.Float(), nullable=True),
        sa.Column(
            "whisper_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("keywords_extracted", sa.Boolean(), nullable=True),
        sa.Column("entities_extracted", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["archive_id"],
            ["radio_archives.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_radio_transcriptions_model",
        "radio_transcriptions",
        ["model_name", "transcribed_at"],
        unique=False,
    )
    op.create_index(
        "idx_radio_transcriptions_quality",
        "radio_transcriptions",
        ["confidence_score", "no_speech_probability"],
        unique=False,
    )
    op.create_index(
        op.f("ix_radio_transcriptions_archive_id"),
        "radio_transcriptions",
        ["archive_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_radio_transcriptions_entities_extracted"),
        "radio_transcriptions",
        ["entities_extracted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_radio_transcriptions_id"), "radio_transcriptions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_radio_transcriptions_keywords_extracted"),
        "radio_transcriptions",
        ["keywords_extracted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_radio_transcriptions_model_name"),
        "radio_transcriptions",
        ["model_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_radio_transcriptions_transcribed_at"),
        "radio_transcriptions",
        ["transcribed_at"],
        unique=False,
    )
    op.create_table(
        "abnormal_patterns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("flight_log_id", sa.Integer(), nullable=False),
        sa.Column("pattern_type", sa.String(length=50), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column(
            "detection_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("reviewed", sa.String(length=10), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column("reviewed_by", sa.String(length=100), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("legal_relevance", sa.String(length=20), nullable=True),
        sa.Column("potential_violation", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["flight_log_id"],
            ["flight_logs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_abnormal_patterns_flight_log_id"),
        "abnormal_patterns",
        ["flight_log_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_abnormal_patterns_id"), "abnormal_patterns", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_abnormal_patterns_pattern_type"),
        "abnormal_patterns",
        ["pattern_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_abnormal_patterns_reviewed"),
        "abnormal_patterns",
        ["reviewed"],
        unique=False,
    )
    op.create_table(
        "flight_positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("flight_log_id", sa.Integer(), nullable=False),
        sa.Column("aircraft_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column("altitude_feet", sa.Integer(), nullable=True),
        sa.Column("ground_elevation_feet", sa.Integer(), nullable=True),
        sa.Column("altitude_agl_feet", sa.Integer(), nullable=True),
        sa.Column("ground_speed_knots", sa.Float(), nullable=True),
        sa.Column("track_degrees", sa.Float(), nullable=True),
        sa.Column("vertical_rate", sa.Float(), nullable=True),
        sa.Column("is_hovering", sa.Boolean(), nullable=True),
        sa.Column("hover_duration_seconds", sa.Integer(), nullable=True),
        sa.Column("is_circling", sa.Boolean(), nullable=True),
        sa.Column("circle_radius_feet", sa.Float(), nullable=True),
        sa.Column("neighborhood", sa.String(length=100), nullable=True),
        sa.Column("address_nearby", sa.String(length=200), nullable=True),
        sa.Column("land_use_type", sa.String(length=50), nullable=True),
        sa.Column("over_private_property", sa.Boolean(), nullable=True),
        sa.Column("altitude_privacy_concern", sa.Boolean(), nullable=True),
        sa.Column("duration_at_location", sa.Integer(), nullable=True),
        sa.Column("position_accuracy_meters", sa.Float(), nullable=True),
        sa.Column("data_source", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["aircraft_id"],
            ["aircraft.id"],
        ),
        sa.ForeignKeyConstraint(
            ["flight_log_id"],
            ["flight_logs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # idx_flight_positions_location is auto-created by geoalchemy2 with the
    # Geography column, so we don't create it explicitly here.
    op.create_index(
        "idx_positions_flight_timestamp",
        "flight_positions",
        ["flight_log_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "idx_positions_hovering",
        "flight_positions",
        ["is_hovering", "hover_duration_seconds"],
        unique=False,
    )
    op.create_index(
        "idx_positions_location",
        "flight_positions",
        ["location"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        op.f("ix_flight_positions_flight_log_id"),
        "flight_positions",
        ["flight_log_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flight_positions_id"), "flight_positions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_flight_positions_timestamp"),
        "flight_positions",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "radio_keywords",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transcription_id", sa.Integer(), nullable=False),
        sa.Column("keyword", sa.String(length=100), nullable=False),
        sa.Column("keyword_type", sa.String(length=50), nullable=True),
        sa.Column("occurrence_count", sa.Integer(), nullable=True),
        sa.Column("first_occurrence_time", sa.Float(), nullable=True),
        sa.Column("context_snippet", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "extracted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["transcription_id"],
            ["radio_transcriptions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_radio_keywords_frequency",
        "radio_keywords",
        ["keyword", "occurrence_count"],
        unique=False,
    )
    op.create_index(
        "idx_radio_keywords_keyword_type",
        "radio_keywords",
        ["keyword", "keyword_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_radio_keywords_id"), "radio_keywords", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_radio_keywords_keyword"), "radio_keywords", ["keyword"], unique=False
    )
    op.create_index(
        op.f("ix_radio_keywords_keyword_type"),
        "radio_keywords",
        ["keyword_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_radio_keywords_transcription_id"),
        "radio_keywords",
        ["transcription_id"],
        unique=False,
    )
    op.create_table(
        "radio_segments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transcription_id", sa.Integer(), nullable=False),
        sa.Column("segment_index", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("end_time", sa.Float(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("absolute_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("no_speech_prob", sa.Float(), nullable=True),
        sa.Column("contains_tail_number", sa.Boolean(), nullable=True),
        sa.Column("contains_location", sa.Boolean(), nullable=True),
        sa.Column("contains_incident_code", sa.Boolean(), nullable=True),
        sa.Column("urgency_score", sa.Float(), nullable=True),
        sa.Column("tail_numbers", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("locations", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("incident_codes", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "segment_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["transcription_id"],
            ["radio_transcriptions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_radio_segments_content_flags",
        "radio_segments",
        ["contains_tail_number", "contains_location", "contains_incident_code"],
        unique=False,
    )
    op.create_index(
        "idx_radio_segments_time",
        "radio_segments",
        ["absolute_timestamp"],
        unique=False,
    )
    op.create_index(
        "idx_radio_segments_transcript_time",
        "radio_segments",
        ["transcription_id", "start_time"],
        unique=False,
    )
    op.create_index(
        "idx_radio_segments_urgency", "radio_segments", ["urgency_score"], unique=False
    )
    op.create_index(
        op.f("ix_radio_segments_absolute_timestamp"),
        "radio_segments",
        ["absolute_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_radio_segments_contains_incident_code"),
        "radio_segments",
        ["contains_incident_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_radio_segments_contains_location"),
        "radio_segments",
        ["contains_location"],
        unique=False,
    )
    op.create_index(
        op.f("ix_radio_segments_contains_tail_number"),
        "radio_segments",
        ["contains_tail_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_radio_segments_id"), "radio_segments", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_radio_segments_transcription_id"),
        "radio_segments",
        ["transcription_id"],
        unique=False,
    )
    op.create_table(
        "flight_radio_correlations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("flight_log_id", sa.Integer(), nullable=False),
        sa.Column("radio_segment_id", sa.Integer(), nullable=False),
        sa.Column("correlation_type", sa.String(length=50), nullable=True),
        sa.Column("correlation_strength", sa.Float(), nullable=True),
        sa.Column("time_difference_seconds", sa.Float(), nullable=True),
        sa.Column("correlation_notes", sa.Text(), nullable=True),
        sa.Column("matched_keywords", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["flight_log_id"],
            ["flight_logs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["radio_segment_id"],
            ["radio_segments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_flight_radio_corr_flight",
        "flight_radio_correlations",
        ["flight_log_id", "correlation_type"],
        unique=False,
    )
    op.create_index(
        "idx_flight_radio_corr_strength",
        "flight_radio_correlations",
        ["correlation_strength"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flight_radio_correlations_correlation_type"),
        "flight_radio_correlations",
        ["correlation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flight_radio_correlations_created_at"),
        "flight_radio_correlations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flight_radio_correlations_flight_log_id"),
        "flight_radio_correlations",
        ["flight_log_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flight_radio_correlations_id"),
        "flight_radio_correlations",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flight_radio_correlations_radio_segment_id"),
        "flight_radio_correlations",
        ["radio_segment_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_flight_radio_correlations_radio_segment_id"),
        table_name="flight_radio_correlations",
    )
    op.drop_index(
        op.f("ix_flight_radio_correlations_id"), table_name="flight_radio_correlations"
    )
    op.drop_index(
        op.f("ix_flight_radio_correlations_flight_log_id"),
        table_name="flight_radio_correlations",
    )
    op.drop_index(
        op.f("ix_flight_radio_correlations_created_at"),
        table_name="flight_radio_correlations",
    )
    op.drop_index(
        op.f("ix_flight_radio_correlations_correlation_type"),
        table_name="flight_radio_correlations",
    )
    op.drop_index(
        "idx_flight_radio_corr_strength", table_name="flight_radio_correlations"
    )
    op.drop_index(
        "idx_flight_radio_corr_flight", table_name="flight_radio_correlations"
    )
    op.drop_table("flight_radio_correlations")
    op.drop_index(
        op.f("ix_radio_segments_transcription_id"), table_name="radio_segments"
    )
    op.drop_index(op.f("ix_radio_segments_id"), table_name="radio_segments")
    op.drop_index(
        op.f("ix_radio_segments_contains_tail_number"), table_name="radio_segments"
    )
    op.drop_index(
        op.f("ix_radio_segments_contains_location"), table_name="radio_segments"
    )
    op.drop_index(
        op.f("ix_radio_segments_contains_incident_code"), table_name="radio_segments"
    )
    op.drop_index(
        op.f("ix_radio_segments_absolute_timestamp"), table_name="radio_segments"
    )
    op.drop_index("idx_radio_segments_urgency", table_name="radio_segments")
    op.drop_index("idx_radio_segments_transcript_time", table_name="radio_segments")
    op.drop_index("idx_radio_segments_time", table_name="radio_segments")
    op.drop_index("idx_radio_segments_content_flags", table_name="radio_segments")
    op.drop_table("radio_segments")
    op.drop_index(
        op.f("ix_radio_keywords_transcription_id"), table_name="radio_keywords"
    )
    op.drop_index(op.f("ix_radio_keywords_keyword_type"), table_name="radio_keywords")
    op.drop_index(op.f("ix_radio_keywords_keyword"), table_name="radio_keywords")
    op.drop_index(op.f("ix_radio_keywords_id"), table_name="radio_keywords")
    op.drop_index("idx_radio_keywords_keyword_type", table_name="radio_keywords")
    op.drop_index("idx_radio_keywords_frequency", table_name="radio_keywords")
    op.drop_table("radio_keywords")
    op.drop_index(op.f("ix_flight_positions_timestamp"), table_name="flight_positions")
    op.drop_index(op.f("ix_flight_positions_id"), table_name="flight_positions")
    op.drop_index(
        op.f("ix_flight_positions_flight_log_id"), table_name="flight_positions"
    )
    op.drop_index(
        "idx_positions_location", table_name="flight_positions", postgresql_using="gist"
    )
    op.drop_index("idx_positions_hovering", table_name="flight_positions")
    op.drop_index("idx_positions_flight_timestamp", table_name="flight_positions")
    op.drop_table("flight_positions")
    op.drop_index(op.f("ix_abnormal_patterns_reviewed"), table_name="abnormal_patterns")
    op.drop_index(
        op.f("ix_abnormal_patterns_pattern_type"), table_name="abnormal_patterns"
    )
    op.drop_index(op.f("ix_abnormal_patterns_id"), table_name="abnormal_patterns")
    op.drop_index(
        op.f("ix_abnormal_patterns_flight_log_id"), table_name="abnormal_patterns"
    )
    op.drop_table("abnormal_patterns")
    op.drop_index(
        op.f("ix_radio_transcriptions_transcribed_at"),
        table_name="radio_transcriptions",
    )
    op.drop_index(
        op.f("ix_radio_transcriptions_model_name"), table_name="radio_transcriptions"
    )
    op.drop_index(
        op.f("ix_radio_transcriptions_keywords_extracted"),
        table_name="radio_transcriptions",
    )
    op.drop_index(op.f("ix_radio_transcriptions_id"), table_name="radio_transcriptions")
    op.drop_index(
        op.f("ix_radio_transcriptions_entities_extracted"),
        table_name="radio_transcriptions",
    )
    op.drop_index(
        op.f("ix_radio_transcriptions_archive_id"), table_name="radio_transcriptions"
    )
    op.drop_index("idx_radio_transcriptions_quality", table_name="radio_transcriptions")
    op.drop_index("idx_radio_transcriptions_model", table_name="radio_transcriptions")
    op.drop_table("radio_transcriptions")
    op.drop_index(op.f("ix_flight_logs_id"), table_name="flight_logs")
    op.drop_index(op.f("ix_flight_logs_flight_id"), table_name="flight_logs")
    op.drop_index(op.f("ix_flight_logs_departure_time"), table_name="flight_logs")
    op.drop_index(op.f("ix_flight_logs_data_source"), table_name="flight_logs")
    op.drop_index(op.f("ix_flight_logs_created_at"), table_name="flight_logs")
    op.drop_index(op.f("ix_flight_logs_callsign"), table_name="flight_logs")
    op.drop_index(op.f("ix_flight_logs_arrival_time"), table_name="flight_logs")
    op.drop_index(op.f("ix_flight_logs_aircraft_id"), table_name="flight_logs")
    op.drop_index("idx_flight_logs_time_range", table_name="flight_logs")
    op.drop_index("idx_flight_logs_surveillance", table_name="flight_logs")
    op.drop_index("idx_flight_logs_aircraft_date", table_name="flight_logs")
    op.drop_table("flight_logs")
    op.drop_index(
        op.f("ix_constitutional_analyses_systematic_surveillance_detected"),
        table_name="constitutional_analyses",
    )
    op.drop_index(
        op.f("ix_constitutional_analyses_surveillance_intensity_score"),
        table_name="constitutional_analyses",
    )
    op.drop_index(
        op.f("ix_constitutional_analyses_legal_document_id"),
        table_name="constitutional_analyses",
    )
    op.drop_index(
        op.f("ix_constitutional_analyses_id"), table_name="constitutional_analyses"
    )
    op.drop_index(
        op.f("ix_constitutional_analyses_discriminatory_impact_detected"),
        table_name="constitutional_analyses",
    )
    op.drop_index(
        op.f("ix_constitutional_analyses_date_range_start"),
        table_name="constitutional_analyses",
    )
    op.drop_index(
        op.f("ix_constitutional_analyses_date_range_end"),
        table_name="constitutional_analyses",
    )
    op.drop_index("idx_const_analysis_violations", table_name="constitutional_analyses")
    op.drop_index("idx_const_analysis_scores", table_name="constitutional_analyses")
    op.drop_index("idx_const_analysis_date_range", table_name="constitutional_analyses")
    op.drop_table("constitutional_analyses")
    op.drop_index(op.f("ix_task_metrics_task_name"), table_name="task_metrics")
    op.drop_index(op.f("ix_task_metrics_id"), table_name="task_metrics")
    op.drop_table("task_metrics")
    op.drop_index(op.f("ix_task_history_task_name"), table_name="task_history")
    op.drop_index(op.f("ix_task_history_task_id"), table_name="task_history")
    op.drop_index(op.f("ix_task_history_status"), table_name="task_history")
    op.drop_index(op.f("ix_task_history_id"), table_name="task_history")
    op.drop_table("task_history")
    op.drop_index(op.f("ix_task_events_task_name"), table_name="task_events")
    op.drop_index(op.f("ix_task_events_task_id"), table_name="task_events")
    op.drop_index(op.f("ix_task_events_id"), table_name="task_events")
    op.drop_index(op.f("ix_task_events_event_type"), table_name="task_events")
    op.drop_index(op.f("ix_task_events_created_at"), table_name="task_events")
    op.drop_table("task_events")
    op.drop_index(op.f("ix_system_logs_source"), table_name="system_logs")
    op.drop_index(op.f("ix_system_logs_registration"), table_name="system_logs")
    op.drop_index(op.f("ix_system_logs_level"), table_name="system_logs")
    op.drop_index(op.f("ix_system_logs_id"), table_name="system_logs")
    op.drop_index(op.f("ix_system_logs_flight_id"), table_name="system_logs")
    op.drop_index(op.f("ix_system_logs_created_at"), table_name="system_logs")
    op.drop_index(op.f("ix_system_logs_category"), table_name="system_logs")
    op.drop_index("idx_logs_level_category", table_name="system_logs")
    op.drop_index("idx_logs_created_level", table_name="system_logs")
    op.drop_index("idx_logs_category_created", table_name="system_logs")
    op.drop_table("system_logs")
    op.drop_index(op.f("ix_system_issues_issue_type"), table_name="system_issues")
    op.drop_index(op.f("ix_system_issues_is_resolved"), table_name="system_issues")
    op.drop_index(op.f("ix_system_issues_id"), table_name="system_issues")
    op.drop_index(op.f("ix_system_issues_error_signature"), table_name="system_issues")
    op.drop_index(op.f("ix_system_issues_component"), table_name="system_issues")
    op.drop_table("system_issues")
    op.drop_index(op.f("ix_radio_archives_transcribed"), table_name="radio_archives")
    op.drop_index(
        op.f("ix_radio_archives_recording_start"), table_name="radio_archives"
    )
    op.drop_index(op.f("ix_radio_archives_recording_end"), table_name="radio_archives")
    op.drop_index(op.f("ix_radio_archives_id"), table_name="radio_archives")
    op.drop_index(op.f("ix_radio_archives_filename"), table_name="radio_archives")
    op.drop_index(op.f("ix_radio_archives_feed_id"), table_name="radio_archives")
    op.drop_index(op.f("ix_radio_archives_downloaded_at"), table_name="radio_archives")
    op.drop_index(op.f("ix_radio_archives_created_at"), table_name="radio_archives")
    op.drop_index(op.f("ix_radio_archives_analyzed"), table_name="radio_archives")
    op.drop_index("idx_radio_archives_time_range", table_name="radio_archives")
    op.drop_index("idx_radio_archives_status", table_name="radio_archives")
    op.drop_index("idx_radio_archives_feed_time", table_name="radio_archives")
    op.drop_table("radio_archives")
    op.drop_index(
        op.f("ix_legal_precedents_surveillance_relevance"),
        table_name="legal_precedents",
    )
    op.drop_index(
        op.f("ix_legal_precedents_jurisdiction"), table_name="legal_precedents"
    )
    op.drop_index(op.f("ix_legal_precedents_id"), table_name="legal_precedents")
    op.drop_index(
        op.f("ix_legal_precedents_decision_date"), table_name="legal_precedents"
    )
    op.drop_index(op.f("ix_legal_precedents_citation"), table_name="legal_precedents")
    op.drop_index(op.f("ix_legal_precedents_case_type"), table_name="legal_precedents")
    op.drop_index(op.f("ix_legal_precedents_case_name"), table_name="legal_precedents")
    op.drop_index(
        op.f("ix_legal_precedents_binding_precedent"), table_name="legal_precedents"
    )
    op.drop_index("idx_precedents_type_jurisdiction", table_name="legal_precedents")
    op.drop_index("idx_precedents_relevance", table_name="legal_precedents")
    op.drop_index("idx_precedents_court_date", table_name="legal_precedents")
    op.drop_table("legal_precedents")
    op.drop_index(op.f("ix_legal_documents_title"), table_name="legal_documents")
    op.drop_index(op.f("ix_legal_documents_id"), table_name="legal_documents")
    op.drop_index(
        op.f("ix_legal_documents_generation_status"), table_name="legal_documents"
    )
    op.drop_index(op.f("ix_legal_documents_generated_at"), table_name="legal_documents")
    op.drop_index(
        op.f("ix_legal_documents_document_type"), table_name="legal_documents"
    )
    op.drop_index(
        op.f("ix_legal_documents_date_range_start"), table_name="legal_documents"
    )
    op.drop_index(
        op.f("ix_legal_documents_date_range_end"), table_name="legal_documents"
    )
    op.drop_index(op.f("ix_legal_documents_created_at"), table_name="legal_documents")
    op.drop_index("idx_legal_docs_type_status", table_name="legal_documents")
    op.drop_index("idx_legal_docs_generated", table_name="legal_documents")
    op.drop_index("idx_legal_docs_date_range", table_name="legal_documents")
    op.drop_table("legal_documents")
    op.drop_index(
        op.f("ix_flight_discoveries_track_downloaded"), table_name="flight_discoveries"
    )
    op.drop_index(
        op.f("ix_flight_discoveries_registration"), table_name="flight_discoveries"
    )
    op.drop_index(op.f("ix_flight_discoveries_id"), table_name="flight_discoveries")
    op.drop_index(
        op.f("ix_flight_discoveries_fr24_id"), table_name="flight_discoveries"
    )
    op.drop_index(
        op.f("ix_flight_discoveries_departure_time"), table_name="flight_discoveries"
    )
    op.drop_table("flight_discoveries")
    op.drop_index(op.f("ix_aircraft_registration"), table_name="aircraft")
    op.drop_index(op.f("ix_aircraft_is_phoenix_pd"), table_name="aircraft")
    op.drop_index(op.f("ix_aircraft_id"), table_name="aircraft")
    op.drop_index(op.f("ix_aircraft_icao_code"), table_name="aircraft")
    op.drop_table("aircraft")
    # ### end Alembic commands ###
