"""Rename metadata to context_metadata in system_logs

Revision ID: fee285f9cbbc
Revises: d20f368f5243
Create Date: 2025-09-27 23:08:06.079039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fee285f9cbbc"
down_revision: Union[str, None] = "d20f368f5243"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Simply rename the metadata column to context_metadata
    op.alter_column(
        "system_logs",
        "metadata",
        new_column_name="context_metadata",
        existing_type=sa.TEXT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename the context_metadata column back to metadata
    op.alter_column(
        "system_logs",
        "context_metadata",
        new_column_name="metadata",
        existing_type=sa.TEXT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
