from typing import List, Optional
from datetime import datetime, timezone
from fastapi import APIRouter, Depends, HTTPException, Query, BackgroundTasks
from sqlalchemy.orm import Session

from app.api.deps import get_db
from app.services.tracking_service import unified_tracking_service
from app.services.flightradar24_api_service import fr24_api_service
from app.services.fr24_sdk_service import fr24_sdk_service
from app.services.fr24_official_api import fr24_official_api
from app.schemas.tracking import (
    LiveTrackingData,
    TrackingAlert,
    TrackingSubscription,
    AircraftTrackingStatus,
    TrackingStats,
    TrackingSource,
)

router = APIRouter()


# Live tracking endpoints
@router.get("/live", response_model=List[LiveTrackingData])
async def get_live_tracking_data(
    *,
    db: Session = Depends(get_db),
    phoenix_pd_only: bool = Query(
        True, description="Filter to Phoenix PD aircraft only"
    ),
    active_only: bool = Query(True, description="Only show currently active aircraft"),
    min_altitude: Optional[int] = Query(None, description="Minimum altitude filter"),
    max_altitude: Optional[int] = Query(None, description="Maximum altitude filter"),
    data_source: Optional[str] = Query(
        None, description="Preferred data source (fr24_api, auto)"
    ),
) -> List[LiveTrackingData]:
    """Get current live tracking data for aircraft using FlightRadar24 SDK"""

    # Try to get real data
    try:
        # Use official FR24 API for real-time data
        if phoenix_pd_only:
            tracking_data = fr24_official_api.get_phoenix_pd_live()
            
            # Apply filters
            if active_only:
                tracking_data = [d for d in tracking_data if d.latitude != 0 and d.longitude != 0]
            if min_altitude is not None:
                tracking_data = [d for d in tracking_data if d.altitude_feet and d.altitude_feet >= min_altitude]
            if max_altitude is not None:
                tracking_data = [d for d in tracking_data if d.altitude_feet and d.altitude_feet <= max_altitude]
                
            if tracking_data:
                import logging
                logging.getLogger(__name__).info(f"Found {len(tracking_data)} Phoenix PD aircraft via SDK")
                return tracking_data
        
        # Fall back to the original service if SDK doesn't find anything
        if data_source == "fr24_api":
            unified_tracking_service.primary_source = TrackingSource.FR24_API
        
        tracking_data = await unified_tracking_service.get_live_tracking_data(
            phoenix_pd_only=phoenix_pd_only,
            active_only=active_only,
            min_altitude=min_altitude,
            max_altitude=max_altitude,
        )

        return tracking_data if tracking_data else []

    except Exception as e:
        import logging

        logging.error(f"Error fetching live tracking data: {e}")
        return []


@router.get("/live/{registration}", response_model=Optional[LiveTrackingData])
async def get_live_aircraft_data(
    *, db: Session = Depends(get_db), registration: str
) -> Optional[LiveTrackingData]:
    """Get live tracking data for specific aircraft using FR24 API"""
    try:
        return await unified_tracking_service.get_aircraft_by_registration(registration)
    except Exception as e:
        import logging

        logging.error(f"Error fetching aircraft data for {registration}: {e}")
        return None


@router.post("/live/refresh")
def refresh_tracking_data(
    *, db: Session = Depends(get_db), background_tasks: BackgroundTasks
) -> dict:
    """Manually refresh tracking data from all sources"""
    # TODO: Implement background task to refresh tracking data
    # background_tasks.add_task(refresh_all_tracking_sources)
    return {"message": "Tracking data refresh initiated", "status": "queued"}


# Alert management endpoints
@router.get("/alerts", response_model=List[TrackingAlert])
def get_tracking_alerts(
    *,
    db: Session = Depends(get_db),
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    alert_type: Optional[str] = Query(None, description="Filter by alert type"),
    severity: Optional[int] = Query(
        None, ge=1, le=5, description="Filter by severity level"
    ),
    active_only: bool = Query(True, description="Only show active alerts"),
    unacknowledged_only: bool = Query(
        False, description="Only show unacknowledged alerts"
    ),
) -> List[TrackingAlert]:
    """Get tracking alerts with optional filtering"""
    # Return empty list when no real alerts are available
    # Real alerts would be generated by the unified tracking service when analyzing actual flight patterns
    return []


@router.post("/alerts/{alert_id}/acknowledge")
def acknowledge_alert(*, db: Session = Depends(get_db), alert_id: str) -> dict:
    """Acknowledge a tracking alert"""
    # TODO: Implement alert acknowledgment
    return {"message": f"Alert {alert_id} acknowledged", "status": "acknowledged"}


@router.post("/alerts/{alert_id}/resolve")
def resolve_alert(
    *,
    db: Session = Depends(get_db),
    alert_id: str,
    resolution_notes: Optional[str] = None,
) -> dict:
    """Mark an alert as resolved"""
    # TODO: Implement alert resolution
    return {"message": f"Alert {alert_id} resolved", "status": "resolved"}


# Subscription management endpoints
@router.get("/subscriptions", response_model=List[TrackingSubscription])
def get_tracking_subscriptions(
    *,
    db: Session = Depends(get_db),
    user_id: Optional[str] = Query(None, description="Filter by user ID"),
    active_only: bool = Query(True, description="Only show active subscriptions"),
) -> List[TrackingSubscription]:
    """Get tracking subscriptions"""
    # TODO: Implement subscription retrieval
    return []


@router.post("/subscriptions", response_model=TrackingSubscription)
def create_tracking_subscription(
    *, db: Session = Depends(get_db), subscription_in: TrackingSubscription
) -> TrackingSubscription:
    """Create new tracking subscription for area alerts"""
    # TODO: Implement subscription creation
    return subscription_in


@router.delete("/subscriptions/{subscription_id}")
def delete_tracking_subscription(
    *, db: Session = Depends(get_db), subscription_id: str
) -> dict:
    """Delete tracking subscription"""
    # TODO: Implement subscription deletion
    return {"message": f"Subscription {subscription_id} deleted", "status": "deleted"}


# Aircraft status endpoints
@router.get("/status", response_model=List[AircraftTrackingStatus])
def get_aircraft_tracking_status(
    *,
    db: Session = Depends(get_db),
    phoenix_pd_only: bool = Query(
        True, description="Filter to Phoenix PD aircraft only"
    ),
) -> List[AircraftTrackingStatus]:
    """Get tracking status for all aircraft"""
    # TODO: Implement aircraft status retrieval
    return []


@router.get("/status/{registration}", response_model=AircraftTrackingStatus)
def get_aircraft_status(
    *, db: Session = Depends(get_db), registration: str
) -> AircraftTrackingStatus:
    """Get tracking status for specific aircraft"""
    # TODO: Implement individual aircraft status
    raise HTTPException(status_code=404, detail="Aircraft status not found")


# Statistics and monitoring endpoints
@router.get("/stats", response_model=TrackingStats)
async def get_tracking_statistics(*, db: Session = Depends(get_db)) -> TrackingStats:
    """Get tracking system statistics"""
    from app.crud.aircraft import aircraft_crud
    from app.crud.flights import flight_log_crud
    from datetime import timedelta

    # Get all Phoenix PD aircraft
    phoenix_aircraft = aircraft_crud.get_phoenix_pd_aircraft(db)
    total_phoenix_aircraft = len(phoenix_aircraft)

    # Get recent flights (last 24 hours)
    now = datetime.now(timezone.utc)
    last_24h = now - timedelta(hours=24)
    recent_flights = flight_log_crud.get_by_date_range(
        db, start_date=last_24h, end_date=now
    )

    # Count active aircraft (flew in last 24h)
    active_aircraft = set()
    for flight in recent_flights:
        active_aircraft.add(flight.aircraft_id)

    # Get today's flights
    today_start = now.replace(hour=0, minute=0, second=0, microsecond=0)
    todays_flights = flight_log_crud.get_by_date_range(
        db, start_date=today_start, end_date=now
    )

    # Count surveillance flights (flights with high surveillance likelihood)
    surveillance_count = sum(
        1
        for f in todays_flights
        if f.surveillance_likelihood and f.surveillance_likelihood > 0.5
    )

    # Calculate costs (estimated $2160/hour for helicopter operations - actual Phoenix PD rate)
    total_hours = sum(
        (f.arrival_time - f.departure_time).total_seconds() / 3600
        for f in todays_flights
        if f.arrival_time and f.departure_time
    )
    total_cost = total_hours * 2160  # $2160 per flight hour (actual Phoenix PD estimate)
    
    # Get LIVE tracking data to count currently active flights
    try:
        # Call the live endpoint directly using the same logic
        live_tracking_data = fr24_official_api.get_phoenix_pd_live()
        current_active_flights = len(live_tracking_data) if live_tracking_data else 0
        helicopters_currently_in_air = current_active_flights
    except Exception as e:
        import logging
        logging.warning(f"Could not get live tracking for stats: {e}")
        current_active_flights = 0
        helicopters_currently_in_air = 0

    # Calculate stats
    return TrackingStats(
        total_aircraft_tracked=total_phoenix_aircraft,
        phoenix_pd_aircraft_active=len(active_aircraft),
        alerts_last_24h=surveillance_count,  # Use surveillance flights as proxy for alerts
        data_sources_active=["FlightRadar24 API", "Database"],
        last_update=datetime.now(timezone.utc),
        tracking_coverage_percent=95.0,  # Estimate based on FR24 coverage
        # Additional fields for frontend
        flights_today=len(todays_flights),
        surveillance_flights_today=surveillance_count,
        total_flight_hours_today=total_hours,
        helicopters_in_air=helicopters_currently_in_air,  # Now using real-time data
        # Dashboard-specific fields
        active_flights=current_active_flights,  # Now using real-time data
        surveillance_incidents_today=surveillance_count,
        total_cost_today=total_cost,
        pattern_alerts=0,  # Would need pattern analysis data
    )


# Historical tracking endpoints
@router.get("/history/{registration}")
def get_aircraft_tracking_history(
    *,
    db: Session = Depends(get_db),
    registration: str,
    start_date: Optional[datetime] = Query(None, description="Start date for history"),
    end_date: Optional[datetime] = Query(None, description="End date for history"),
    limit: int = Query(1000, ge=1, le=10000, description="Maximum number of positions"),
) -> dict:
    """Get historical tracking data for aircraft"""
    # This would return flight positions and logs for the aircraft
    # TODO: Integrate with flight_position_crud to get actual data
    return {
        "aircraft_registration": registration,
        "date_range": {"start": start_date, "end": end_date},
        "positions": [],
        "flights": [],
        "total_positions": 0,
        "total_flights": 0,
    }


# Configuration endpoints
@router.get("/config")
def get_tracking_configuration() -> dict:
    """Get current tracking system configuration"""
    return {
        "flightradar24": {
            "enabled": True,
            "subscription_active": True,
            "historical_data_available": True,
        },
        "geographic_bounds": {
            "center_lat": 33.4484,
            "center_lon": -112.0740,
            "radius_km": 50,
        },
        "alert_thresholds": {
            "low_altitude_feet": 400,
            "hover_duration_seconds": 30,
            "residential_overflight_concern": True,
        },
    }


@router.post("/config/update")
def update_tracking_configuration(
    *, db: Session = Depends(get_db), config_updates: dict
) -> dict:
    """Update tracking system configuration"""
    # TODO: Implement configuration updates
    return {"message": "Configuration updated", "status": "updated"}


# Data source management
@router.post("/sources/flightradar24/import")
def import_flightradar24_data(
    *,
    db: Session = Depends(get_db),
    background_tasks: BackgroundTasks,
    file_path: str,
    aircraft_registration: str,
    file_format: str = "kml",
) -> dict:
    """Import historical data from FlightRadar24"""
    # TODO: Implement FlightRadar24 data import
    # background_tasks.add_task(import_fr24_file, file_path, aircraft_registration, file_format)
    return {
        "message": "Import started",
        "status": "processing",
        "aircraft_registration": aircraft_registration,
        "file_format": file_format,
    }


@router.get("/sources/status")
async def get_data_sources_status() -> dict:
    """Get status of all data sources including credit usage"""
    return await unified_tracking_service.get_service_status()


@router.get("/sources/fr24/credits")
async def get_fr24_credit_usage() -> dict:
    """Get FlightRadar24 API credit usage statistics"""
    try:
        async with fr24_api_service:
            if fr24_api_service.credit_manager:
                return await fr24_api_service.credit_manager.get_usage_stats()
            else:
                return {"error": "Credit manager not initialized"}
    except Exception as e:
        return {"error": str(e)}
